# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f79419e4d0eb101e502274d88dc2a4e3e2801f637476144e4e975b746dddde2fd0599c0f5eb2fd493a35bfe623d9d7ef5633dc1f8ac782a82a108dbfd935ea59

test:
  secret_key_base: 1ceaf56414fd92fb18256427162378ddfe248a05fb505e642452a5cdc14dc9efa877557baa8bc2a1c1497a4fecea8327141440725efdb868cd50166795f0752e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
